[package]
name = "pi_calculator_lib_ir"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.100"
js-sys = "0.3.70"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
